
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author said
 */
public class GuessingGame_main extends javax.swing.JFrame {

    private int hak=9;
    int girdi=0,say=0,say1=3,say2=7,say3=5;
        RandomValue random = new RandomValue();//RandomValue classımızdan random diye bir nesne oluşturuyoruz.
        boolean a=random.RandomValueProduce();
        int random_value = random.randomValueControl();//randomValueControl metotu içinde hem random sayı atattırıyoruz hemde bu random sayıyının içinde aynı rakam varmı diye kontrol ediyor. Varsa yeniden random deger üretiyor. 
        Comparison comparison = new Comparison();//comparison classında random sayı ile girilen sayiyi karsılastırıp aynı basamakda aynı olan rakam sayısını sayarız
        Comparison2 comparison2 = new Comparison2();//comparison2 classında random sayi ile girilen sayiyi karsılastırıp aynı basamakda olmayıpda aynı olan rakamları sayarız
                        
        
        /**
     * Creates new form GuessingGame_main
     */
    public GuessingGame_main() {
        initComponents();
        TimerTask timerTask = new TimerTask() {
           @Override 
           public void run() { 
               label1.setForeground(Color.YELLOW);
               label2.setForeground(Color.cyan);
               label3.setForeground(Color.GREEN);
               label4.setForeground(Color.BLUE);
               label1.setText(Integer.toString(say));
               label2.setText(Integer.toString(say1));
               label3.setText(Integer.toString(say2));
               label4.setText(Integer.toString(say3));
               say++;
               say1++;
               say2++;
               say3++;
               
               if(girdi==2 && say>9){
                   cancel();
                   label1.setForeground(Color.red);
               label2.setForeground(Color.red);
               label3.setForeground(Color.red);
               label4.setForeground(Color.red);
                   label1.setText("?");
                   label2.setText("?");
                   label3.setText("?");
                   label4.setText("?");
               }
               else if(say>9){
               say=0;
               girdi++;
               }
               if(say1>9){
                   say1=0;
               }
                if(say2>9){
                   say2=0;
               }
                 if(say3>9){
                   say3=0;
               }
               }
           };
          Timer timer = new Timer();
          timer.schedule(timerTask, 0, 100);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        text_number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guessing Game");
        setMinimumSize(new java.awt.Dimension(415, 400));
        setName("Frame1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(10, 3, 3));
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        text_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_numberActionPerformed(evt);
            }
        });

        jButton1.setText("TAHMİN ET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(242, 9, 9));
        label1.setText("?");

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(242, 9, 9));
        label2.setText("?");

        label3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(242, 9, 9));
        label3.setText("?");

        label4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label4.setForeground(new java.awt.Color(242, 9, 9));
        label4.setText("?");

        jMenu1.setText("Bilgi");

        jMenuItem1.setText("Nasıl Oynanır");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Yapımcılar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Başlat");

        jMenuItem3.setText("Yeniden Başlat");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Tutulan Sayi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_number)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(text_number, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void text_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_numberActionPerformed
        // TODO add your handling code here:
              jButton1ActionPerformed(evt);
    }//GEN-LAST:event_text_numberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean hata=true;
        if(hak==1){
            JOptionPane.showMessageDialog(this, "hakkınız bitmiştir!! Cevap => "+random.getValeu());
            int reply;
        reply=JOptionPane.showConfirmDialog(rootPane, "Yeniden oynamak ister misiniz?");
        
        if(reply ==1)
        {
            JOptionPane.showMessageDialog(rootPane, "Teşekkürler.. Tekrar beklerim :)");
            this.dispose();
        }else{
         this.dispose();
         String [] a=new String[5];
         main(a);
        }
        }
        
        try {
                        int sayi = 0, denemesayisi = 0, girilendeaynırakamsayacı = 0;
                        
                        int[] sayidizisi = new int[4];//girilen sayinin rakamlarını bu dizide tutacagız
                        
                        
                        {
                            denemesayisi++;
                            
                                        girilendeaynırakamsayacı = 0;
                                        try {
                                            sayi = Integer.parseInt(text_number.getText());
                                            sayidizisi = comparison.girilenbasamaklarınaayır(sayi);
                                            for (int i = 0; i < 4; i++) {
                                                for (int j = 0; j < 4; j++) {
                                                    if (sayidizisi[j] == (sayidizisi[i]) && i != j) {
                                                        girilendeaynırakamsayacı = 1;
                                                        break;
                                                    }
                                                    if (girilendeaynırakamsayacı == 1) {
                                                        break;
                                                    }

                                                }
                                        }

                                        if (sayi < 1000) {
                                            hata=false;
                                            JOptionPane.showMessageDialog(null, "YANLIŞ DEĞER GİRDİNİZ!! LÜTFEN 4 BASAMAKLI BİR SAYİ GİRİNİZ!!");
                                        } else if (girilendeaynırakamsayacı == 1) {
                                            hata=false;
                                            JOptionPane.showMessageDialog(null, "LÜTFEN FARKLI RAKAMLAR İÇEREN SAYİ GİRİNİZ!!");
                                        } else if (sayi > 9999) {
                                            hata=false;
                                            JOptionPane.showMessageDialog(null, "YANLIŞ DEĞER GİRDİNİZ!! LÜTFEN 4 BASAMAKLI BİR SAYİ GİRİNİZ!!");
                                        }
                                        } catch (Exception e) {
                                            hata=false;
                                            JOptionPane.showMessageDialog(null, "LÜTFEN 4 BASAMAKLI BİR SAYİ GİRİNİZ!!");
                                       }
                                        
                            if(hata==true){
                                hak--;
                                jTextArea1.append("*****************************\n");
                                jTextArea1.append("Kalan Tahmin hakkınız " + (hak) + "\nYazdığınız sayi => "+sayi+"\n");
                            if (comparison.compari(sayi, random_value) == 4) {
                                JOptionPane.showMessageDialog(null, "TEBRİKLER DOĞRU SAYI!!! " + denemesayisi + ". denemede buldunuz..");
                              } else {
                                jTextArea1.append(comparison.compari(sayi, random_value) + " tane rakam doğru basamaktadır..\n" + comparison2.comparison(sayi, random_value) + " tane rakamın basamağı yanlıştır.." + "\n*****************************\n");
                            }    
                            }
                            

                        }
                       }catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Program sonlandırıldı....");
                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Merhaba Arkadaşlar Öncelikle oyun\noyuncudan dört basamaklı rakamları\nfarklı bir sayıyı girmenizi istiyor \ndaha sonra tahmininizde doğru olan\nrakamları ve yerleri yanlış olan \nrakamları belirtiyor kullanıcı bu "
                + "\nsayılara paralel başka tahminlerde\n"
                + "bulunarak doğru olan rakamların basamak \n"
                + "yerlerini tam olarak saptamaya çalışıyor \n"
                + "kullanıcı kendisine verilen 8 tahmin \n"
                + "hakkından sonra o sayıyı tutturmaya çalışıyor .\n" +
"\n" + "Bu oyun başlangıç seviyesindedir\nbu oyunu ilerleyen zamanda \ngeliştirmeye devam edeceğiz.."+"\n\nKeyifle oynamanız dileği ile..");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Mehmet DiK => https://github.com/mehmetdik\n"
                + "Said ALTINTOP => https://github.com/saltintop64\n");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        int reply;
        reply=JOptionPane.showConfirmDialog(rootPane, "Yeniden başlatmak istediğinize emin misiniz?");
        if (reply == 0) {
         this.dispose();
         String [] a=new String[5];
         main(a);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "İptal edildi..Oynunuz devam ediyor..");
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int reply;
        reply=JOptionPane.showConfirmDialog(rootPane, "Eğer tutulan sayiyi görürseniz oyun yeniden başlar..\nDevam etmek istediğinize emin misiniz?");
        if (reply == 0) {
         JOptionPane.showMessageDialog(rootPane, "Tutulan sayi => "+random.getValeu());
         this.dispose();
         String [] a=new String[5];
         main(a);
        }
        else
            JOptionPane.showMessageDialog(rootPane, "İptal edildi..Oynunuz devam ediyor..");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new GuessingGame_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JTextField text_number;
    // End of variables declaration//GEN-END:variables
}
